### PR TITLE
Fix __hash__ method to deal with sets and maps

### PR DESCRIPTION
**Pull request by lucasmarshall**
@mlmorg @sectioneight @samongoose new diff based off uber-master branch

### CODE REVIEW

**Comment by samongoose** [comment]
lg2m as long as we intend to support hashes.

**Comment by toddsifleet** [comment]
:+1:

**Comment by breerly** [comment]
@lucasmarshall can you update the PR with a description of the why/what. Also, are you going to upstream this?

**Comment by xyh** [comment]
+1

**Comment by lucasmarshall** [comment]
@samongoose This was not an issue with supporting maps/sets as hash keys.

Only did this because I had issues with `__hash__()` just using generated client/server types for the following type definitions:

    struct Product {
        1: string name
        2: UUID product_type_uuid
        3: UUID uuid
        4: UUID geofence_uuid
        5: UUID namespace_uuid
        6: map<string,RuleSet> properties
    }

    struct ProductsResponse {
        1: set<Product> products
    }

**Comment by lucasmarshall** [comment]
I'm actually very surprised that no one else ran into this issue. Just using `set<>` or `map<>` types as the type for any struct field caused issues.

**Comment by lucasmarshall** [comment]
@breerly commit message updated as requested. I can submit this upstream as well, certainly. I'm sure others are running into the same issues as I am here, so it likely would be welcomed.

**Comment by chucknthem** [comment]
Can we merge this now?

**Comment by breerly** [comment]
I don't think we're actually using our own generated code yet, only the thrift python library.

**Comment by chucknthem** [comment]
Products is using this, right now we're using a custom compiled thrift binary so that our generated code doesn't throw

**Comment by breerly** [comment]
About to RIP this repo - please work with @prashantv if you have Go Thrift-needs, else use the thriftrw repos: https://github.com/search?utf8=%E2%9C%93&q=thriftrw

**Pull request closed without merging**
