### PR TITLE
Wrap Python THttpClient withTimeout in a try/finally

### PR DESCRIPTION
**Pull request by breerly**
Let's bring this fix into our own 0.9.2 fork, since Apache is likely to take a bit getting 0.9.3.

I recreated this commit:
https://github.com/apache/thrift/pull/322/commits

### CODE REVIEW

**Comment by sectioneight** [comment]
Not sure you want to pull into master. We should make a branch off the latest stable release.

**Comment by breerly** [comment]
Aah good point.

**Comment by breerly** [comment]
@sh1mmer which branch are we going to distribute our fork of thrift from? Looks like your PR's have been going to `safety-and-doubles-tcompact`? That's an odd name for all our commits to end up, what about `uber-master`?

**Comment by breerly** [comment]
Going to re-open this PR to `uber-master`.

**Pull request closed without merging**
