### PR TITLE
propogate transport exceptions for TTornado HTTP client

### PR DESCRIPTION
**Pull request by shirchen**
@abhinav @blampe @breerly

### CODE REVIEW

**Comment by abhinav** [comment]
LGTM

**Comment by blampe** [comment]
Is it really safe to bundle all of these up as EOF errors? Isn't this a breaking change?

**Comment by abhinav** [comment]
This isn't a breaking change. It's a bug fix. The generated code doesn't expect `transport.readFrame()` to raise anything but `TTransportException` and `TException`. Anything else will cause the future to not get filled and the request will freeze/time out. This is a fix for our handling of actual transport exceptions while making the HTTP request. We can make the exception more specific if you think `Exception` is too wide but that'll mean non-debuggable freezing requests if any other exception get raised.

**Comment by blampe** [comment]
Cool go for it :)

**Pull request merged**
